#ifndef SGL_CORE_BASE_H_
#define SGL_CORE_BASE_H_

#define SGL_STRINGIFY(x) #x

// TODO into CMake?
#define SGL_GL_MAJOR_VERSION 4
#define SGL_GL_MINOR_VERSION 5


#define SGL_WINDOW_DEFAULT_WIDTH  1280
#define SGL_WINDOW_DEFAULT_HEIGHT 720 
#define SGL_WINDOW_DEFAULT_TITLE "Application"


#endif // SGL_CORE_BASE_H_